# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/ui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1050, 752)
        icon = QtGui.QIcon.fromTheme("applications-internet")
        MainWindow.setWindowIcon(icon)
        self.ui_centralwidget = QtWidgets.QWidget(MainWindow)
        self.ui_centralwidget.setObjectName("ui_centralwidget")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.ui_centralwidget)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.ui_tabs = QtWidgets.QTabWidget(self.ui_centralwidget)
        self.ui_tabs.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ui_tabs.setMovable(True)
        self.ui_tabs.setObjectName("ui_tabs")
        self.ui_console_tab = QtWidgets.QWidget()
        self.ui_console_tab.setFocusPolicy(QtCore.Qt.TabFocus)
        self.ui_console_tab.setObjectName("ui_console_tab")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.ui_console_tab)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ui_console_layout = QtWidgets.QVBoxLayout()
        self.ui_console_layout.setObjectName("ui_console_layout")
        self.horizontalLayout_4.addLayout(self.ui_console_layout)
        icon = QtGui.QIcon.fromTheme("utilities-terminal")
        self.ui_tabs.addTab(self.ui_console_tab, icon, "")
        self.ui_dispatchers_tab = QtWidgets.QWidget()
        self.ui_dispatchers_tab.setObjectName("ui_dispatchers_tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.ui_dispatchers_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.ui_dispatchers_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ui_dispatch_table_dispatch = QtWidgets.QTableView(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_dispatch_table_dispatch.sizePolicy().hasHeightForWidth())
        self.ui_dispatch_table_dispatch.setSizePolicy(sizePolicy)
        self.ui_dispatch_table_dispatch.setObjectName("ui_dispatch_table_dispatch")
        self.verticalLayout_5.addWidget(self.ui_dispatch_table_dispatch)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ui_dispatch_btn_dispatch_clear_local = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_dispatch_btn_dispatch_clear_local.sizePolicy().hasHeightForWidth())
        self.ui_dispatch_btn_dispatch_clear_local.setSizePolicy(sizePolicy)
        self.ui_dispatch_btn_dispatch_clear_local.setMinimumSize(QtCore.QSize(0, 40))
        icon = QtGui.QIcon.fromTheme("view-refresh")
        self.ui_dispatch_btn_dispatch_clear_local.setIcon(icon)
        self.ui_dispatch_btn_dispatch_clear_local.setObjectName("ui_dispatch_btn_dispatch_clear_local")
        self.horizontalLayout_2.addWidget(self.ui_dispatch_btn_dispatch_clear_local)
        self.ui_dispatch_btn_dispatch_clear_queue = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_dispatch_btn_dispatch_clear_queue.sizePolicy().hasHeightForWidth())
        self.ui_dispatch_btn_dispatch_clear_queue.setSizePolicy(sizePolicy)
        self.ui_dispatch_btn_dispatch_clear_queue.setMinimumSize(QtCore.QSize(0, 40))
        icon = QtGui.QIcon.fromTheme("process-stop")
        self.ui_dispatch_btn_dispatch_clear_queue.setIcon(icon)
        self.ui_dispatch_btn_dispatch_clear_queue.setObjectName("ui_dispatch_btn_dispatch_clear_queue")
        self.horizontalLayout_2.addWidget(self.ui_dispatch_btn_dispatch_clear_queue)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.ui_dispatch_label_dispatch_stats = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_dispatch_label_dispatch_stats.sizePolicy().hasHeightForWidth())
        self.ui_dispatch_label_dispatch_stats.setSizePolicy(sizePolicy)
        self.ui_dispatch_label_dispatch_stats.setScaledContents(True)
        self.ui_dispatch_label_dispatch_stats.setObjectName("ui_dispatch_label_dispatch_stats")
        self.horizontalLayout_2.addWidget(self.ui_dispatch_label_dispatch_stats)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.gridLayout_5.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.ui_dispatchers_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.ui_dispatchers_tbl_loads = QtWidgets.QTableView(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_dispatchers_tbl_loads.sizePolicy().hasHeightForWidth())
        self.ui_dispatchers_tbl_loads.setSizePolicy(sizePolicy)
        self.ui_dispatchers_tbl_loads.setObjectName("ui_dispatchers_tbl_loads")
        self.gridLayout_4.addWidget(self.ui_dispatchers_tbl_loads, 0, 1, 1, 1)
        self.ui_dispatchers_tbl_files = QtWidgets.QTableView(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.ui_dispatchers_tbl_files.sizePolicy().hasHeightForWidth())
        self.ui_dispatchers_tbl_files.setSizePolicy(sizePolicy)
        self.ui_dispatchers_tbl_files.setObjectName("ui_dispatchers_tbl_files")
        self.gridLayout_4.addWidget(self.ui_dispatchers_tbl_files, 2, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 1, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ui_dispatchers_btn_load = QtWidgets.QPushButton(self.groupBox_3)
        self.ui_dispatchers_btn_load.setMinimumSize(QtCore.QSize(0, 40))
        icon = QtGui.QIcon.fromTheme("mail-send")
        self.ui_dispatchers_btn_load.setIcon(icon)
        self.ui_dispatchers_btn_load.setObjectName("ui_dispatchers_btn_load")
        self.verticalLayout_2.addWidget(self.ui_dispatchers_btn_load)
        self.ui_dispatchers_btn_upload = QtWidgets.QPushButton(self.groupBox_3)
        icon = QtGui.QIcon.fromTheme("mail-message-new")
        self.ui_dispatchers_btn_upload.setIcon(icon)
        self.ui_dispatchers_btn_upload.setObjectName("ui_dispatchers_btn_upload")
        self.verticalLayout_2.addWidget(self.ui_dispatchers_btn_upload)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 2, 0, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.ui_dispatchers_btn_abort = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_dispatchers_btn_abort.sizePolicy().hasHeightForWidth())
        self.ui_dispatchers_btn_abort.setSizePolicy(sizePolicy)
        self.ui_dispatchers_btn_abort.setMinimumSize(QtCore.QSize(0, 40))
        self.ui_dispatchers_btn_abort.setAutoFillBackground(False)
        icon = QtGui.QIcon.fromTheme("mail-mark-important")
        self.ui_dispatchers_btn_abort.setIcon(icon)
        self.ui_dispatchers_btn_abort.setIconSize(QtCore.QSize(16, 16))
        self.ui_dispatchers_btn_abort.setDefault(False)
        self.ui_dispatchers_btn_abort.setFlat(False)
        self.ui_dispatchers_btn_abort.setObjectName("ui_dispatchers_btn_abort")
        self.verticalLayout_9.addWidget(self.ui_dispatchers_btn_abort)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem3)
        self.gridLayout_4.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_3, 0, 2, 1, 1)
        icon = QtGui.QIcon.fromTheme("emblem-shared")
        self.ui_tabs.addTab(self.ui_dispatchers_tab, icon, "")
        self.ui_log_tab = QtWidgets.QWidget()
        self.ui_log_tab.setEnabled(True)
        self.ui_log_tab.setObjectName("ui_log_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.ui_log_tab)
        self.gridLayout.setObjectName("gridLayout")
        self.ui_log_gsed_list = QtWidgets.QListWidget(self.ui_log_tab)
        self.ui_log_gsed_list.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(12)
        self.ui_log_gsed_list.setFont(font)
        self.ui_log_gsed_list.setAutoFillBackground(False)
        self.ui_log_gsed_list.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ui_log_gsed_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.ui_log_gsed_list.setWordWrap(True)
        self.ui_log_gsed_list.setObjectName("ui_log_gsed_list")
        self.gridLayout.addWidget(self.ui_log_gsed_list, 5, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ui_log_gsed_lbl = QtWidgets.QLabel(self.ui_log_tab)
        self.ui_log_gsed_lbl.setObjectName("ui_log_gsed_lbl")
        self.horizontalLayout.addWidget(self.ui_log_gsed_lbl)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.ui_log_gsed_clear = QtWidgets.QPushButton(self.ui_log_tab)
        self.ui_log_gsed_clear.setMinimumSize(QtCore.QSize(100, 0))
        self.ui_log_gsed_clear.setObjectName("ui_log_gsed_clear")
        self.horizontalLayout.addWidget(self.ui_log_gsed_clear)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        icon = QtGui.QIcon.fromTheme("utilities-system-monitor")
        self.ui_tabs.addTab(self.ui_log_tab, icon, "")
        self.ui_command_load_tab = QtWidgets.QWidget()
        self.ui_command_load_tab.setObjectName("ui_command_load_tab")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.ui_command_load_tab)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.ui_commandload_available_tbl = QtWidgets.QTableView(self.ui_command_load_tab)
        self.ui_commandload_available_tbl.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.ui_commandload_available_tbl.setAlternatingRowColors(False)
        self.ui_commandload_available_tbl.setObjectName("ui_commandload_available_tbl")
        self.ui_commandload_available_tbl.horizontalHeader().setDefaultSectionSize(90)
        self.ui_commandload_available_tbl.horizontalHeader().setMinimumSectionSize(90)
        self.ui_commandload_available_tbl.horizontalHeader().setStretchLastSection(True)
        self.ui_commandload_available_tbl.verticalHeader().setVisible(False)
        self.ui_commandload_available_tbl.verticalHeader().setCascadingSectionResizes(True)
        self.gridLayout_13.addWidget(self.ui_commandload_available_tbl, 1, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.ui_commandload_label_staged = QtWidgets.QLabel(self.ui_command_load_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_commandload_label_staged.sizePolicy().hasHeightForWidth())
        self.ui_commandload_label_staged.setSizePolicy(sizePolicy)
        self.ui_commandload_label_staged.setObjectName("ui_commandload_label_staged")
        self.horizontalLayout_9.addWidget(self.ui_commandload_label_staged)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.ui_commandload_btn_unstage = QtWidgets.QPushButton(self.ui_command_load_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_commandload_btn_unstage.sizePolicy().hasHeightForWidth())
        self.ui_commandload_btn_unstage.setSizePolicy(sizePolicy)
        self.ui_commandload_btn_unstage.setMinimumSize(QtCore.QSize(64, 0))
        self.ui_commandload_btn_unstage.setText("")
        icon = QtGui.QIcon.fromTheme("up")
        self.ui_commandload_btn_unstage.setIcon(icon)
        self.ui_commandload_btn_unstage.setObjectName("ui_commandload_btn_unstage")
        self.horizontalLayout_9.addWidget(self.ui_commandload_btn_unstage)
        self.ui_commandload_btn_stage = QtWidgets.QPushButton(self.ui_command_load_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_commandload_btn_stage.sizePolicy().hasHeightForWidth())
        self.ui_commandload_btn_stage.setSizePolicy(sizePolicy)
        self.ui_commandload_btn_stage.setMinimumSize(QtCore.QSize(64, 0))
        self.ui_commandload_btn_stage.setText("")
        icon = QtGui.QIcon.fromTheme("down")
        self.ui_commandload_btn_stage.setIcon(icon)
        self.ui_commandload_btn_stage.setObjectName("ui_commandload_btn_stage")
        self.horizontalLayout_9.addWidget(self.ui_commandload_btn_stage)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.gridLayout_13.addLayout(self.horizontalLayout_9, 2, 0, 1, 1)
        self.ui_commandload_staged_tbl = QtWidgets.QTableView(self.ui_command_load_tab)
        self.ui_commandload_staged_tbl.setObjectName("ui_commandload_staged_tbl")
        self.ui_commandload_staged_tbl.horizontalHeader().setDefaultSectionSize(90)
        self.ui_commandload_staged_tbl.horizontalHeader().setMinimumSectionSize(90)
        self.ui_commandload_staged_tbl.horizontalHeader().setStretchLastSection(True)
        self.ui_commandload_staged_tbl.verticalHeader().setCascadingSectionResizes(True)
        self.gridLayout_13.addWidget(self.ui_commandload_staged_tbl, 3, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem7)
        self.ui_commandload_btn_up = QtWidgets.QPushButton(self.ui_command_load_tab)
        self.ui_commandload_btn_up.setObjectName("ui_commandload_btn_up")
        self.verticalLayout_7.addWidget(self.ui_commandload_btn_up)
        self.ui_commandload_btn_down = QtWidgets.QPushButton(self.ui_command_load_tab)
        self.ui_commandload_btn_down.setObjectName("ui_commandload_btn_down")
        self.verticalLayout_7.addWidget(self.ui_commandload_btn_down)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem8)
        self.ui_commandload_btn_export = QtWidgets.QPushButton(self.ui_command_load_tab)
        self.ui_commandload_btn_export.setObjectName("ui_commandload_btn_export")
        self.verticalLayout_7.addWidget(self.ui_commandload_btn_export)
        self.gridLayout_13.addLayout(self.verticalLayout_7, 3, 3, 1, 1)
        self.ui_commandload_label_available = QtWidgets.QLabel(self.ui_command_load_tab)
        self.ui_commandload_label_available.setObjectName("ui_commandload_label_available")
        self.gridLayout_13.addWidget(self.ui_commandload_label_available, 0, 0, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem9)
        self.ui_commandload_btn_load = QtWidgets.QPushButton(self.ui_command_load_tab)
        icon = QtGui.QIcon.fromTheme("folder-open")
        self.ui_commandload_btn_load.setIcon(icon)
        self.ui_commandload_btn_load.setObjectName("ui_commandload_btn_load")
        self.verticalLayout_8.addWidget(self.ui_commandload_btn_load)
        self.ui_commandload_btn_delete = QtWidgets.QPushButton(self.ui_command_load_tab)
        icon = QtGui.QIcon.fromTheme("edit-delete")
        self.ui_commandload_btn_delete.setIcon(icon)
        self.ui_commandload_btn_delete.setObjectName("ui_commandload_btn_delete")
        self.verticalLayout_8.addWidget(self.ui_commandload_btn_delete)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem10)
        self.gridLayout_13.addLayout(self.verticalLayout_8, 1, 3, 1, 1)
        icon = QtGui.QIcon.fromTheme("text-x-script")
        self.ui_tabs.addTab(self.ui_command_load_tab, icon, "")
        self.ui_interfaces_tab = QtWidgets.QWidget()
        self.ui_interfaces_tab.setObjectName("ui_interfaces_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.ui_interfaces_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ui_interfaces_devices_grp = QtWidgets.QGroupBox(self.ui_interfaces_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_interfaces_devices_grp.sizePolicy().hasHeightForWidth())
        self.ui_interfaces_devices_grp.setSizePolicy(sizePolicy)
        self.ui_interfaces_devices_grp.setObjectName("ui_interfaces_devices_grp")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.ui_interfaces_devices_grp)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.ui_interfaces_devices_tbl = QtWidgets.QTableView(self.ui_interfaces_devices_grp)
        self.ui_interfaces_devices_tbl.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.ui_interfaces_devices_tbl.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.ui_interfaces_devices_tbl.setObjectName("ui_interfaces_devices_tbl")
        self.ui_interfaces_devices_tbl.horizontalHeader().setDefaultSectionSize(130)
        self.ui_interfaces_devices_tbl.horizontalHeader().setMinimumSectionSize(100)
        self.ui_interfaces_devices_tbl.horizontalHeader().setStretchLastSection(True)
        self.ui_interfaces_devices_tbl.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_6.addWidget(self.ui_interfaces_devices_tbl)
        self.ui_interfaces_devices_btn_layout = QtWidgets.QHBoxLayout()
        self.ui_interfaces_devices_btn_layout.setObjectName("ui_interfaces_devices_btn_layout")
        self.ui_interfaces_devices_btn_scan = QtWidgets.QPushButton(self.ui_interfaces_devices_grp)
        self.ui_interfaces_devices_btn_scan.setObjectName("ui_interfaces_devices_btn_scan")
        self.ui_interfaces_devices_btn_layout.addWidget(self.ui_interfaces_devices_btn_scan)
        self.ui_interfaces_devices_btn_activate = QtWidgets.QPushButton(self.ui_interfaces_devices_grp)
        self.ui_interfaces_devices_btn_activate.setObjectName("ui_interfaces_devices_btn_activate")
        self.ui_interfaces_devices_btn_layout.addWidget(self.ui_interfaces_devices_btn_activate)
        self.ui_interfaces_devices_btn_connect_send = QtWidgets.QPushButton(self.ui_interfaces_devices_grp)
        self.ui_interfaces_devices_btn_connect_send.setObjectName("ui_interfaces_devices_btn_connect_send")
        self.ui_interfaces_devices_btn_layout.addWidget(self.ui_interfaces_devices_btn_connect_send)
        self.ui_interfaces_devices_btn_connect_recv = QtWidgets.QPushButton(self.ui_interfaces_devices_grp)
        self.ui_interfaces_devices_btn_connect_recv.setObjectName("ui_interfaces_devices_btn_connect_recv")
        self.ui_interfaces_devices_btn_layout.addWidget(self.ui_interfaces_devices_btn_connect_recv)
        self.verticalLayout_6.addLayout(self.ui_interfaces_devices_btn_layout)
        self.ui_interfaces_sending_kiss_grp = QtWidgets.QGroupBox(self.ui_interfaces_devices_grp)
        self.ui_interfaces_sending_kiss_grp.setObjectName("ui_interfaces_sending_kiss_grp")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.ui_interfaces_sending_kiss_grp)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.ui_interfaces_sending_kiss_edit_port = QtWidgets.QLineEdit(self.ui_interfaces_sending_kiss_grp)
        self.ui_interfaces_sending_kiss_edit_port.setEnabled(True)
        self.ui_interfaces_sending_kiss_edit_port.setMaximumSize(QtCore.QSize(150, 16777215))
        self.ui_interfaces_sending_kiss_edit_port.setMaxLength(5)
        self.ui_interfaces_sending_kiss_edit_port.setFrame(True)
        self.ui_interfaces_sending_kiss_edit_port.setClearButtonEnabled(False)
        self.ui_interfaces_sending_kiss_edit_port.setObjectName("ui_interfaces_sending_kiss_edit_port")
        self.gridLayout_17.addWidget(self.ui_interfaces_sending_kiss_edit_port, 1, 1, 1, 1)
        self.ui_interfaces_sending_kiss_btn_add = QtWidgets.QPushButton(self.ui_interfaces_sending_kiss_grp)
        self.ui_interfaces_sending_kiss_btn_add.setObjectName("ui_interfaces_sending_kiss_btn_add")
        self.gridLayout_17.addWidget(self.ui_interfaces_sending_kiss_btn_add, 1, 2, 1, 1)
        self.ui_interfaces_sending_kiss_lbl_port = QtWidgets.QLabel(self.ui_interfaces_sending_kiss_grp)
        self.ui_interfaces_sending_kiss_lbl_port.setMaximumSize(QtCore.QSize(150, 16777215))
        self.ui_interfaces_sending_kiss_lbl_port.setObjectName("ui_interfaces_sending_kiss_lbl_port")
        self.gridLayout_17.addWidget(self.ui_interfaces_sending_kiss_lbl_port, 0, 1, 1, 1)
        self.ui_interfaces_sending_kiss_edit_host = QtWidgets.QLineEdit(self.ui_interfaces_sending_kiss_grp)
        self.ui_interfaces_sending_kiss_edit_host.setEnabled(False)
        self.ui_interfaces_sending_kiss_edit_host.setObjectName("ui_interfaces_sending_kiss_edit_host")
        self.gridLayout_17.addWidget(self.ui_interfaces_sending_kiss_edit_host, 1, 0, 1, 1)
        self.ui_interfaces_sending_kiss_lbl_host = QtWidgets.QLabel(self.ui_interfaces_sending_kiss_grp)
        self.ui_interfaces_sending_kiss_lbl_host.setObjectName("ui_interfaces_sending_kiss_lbl_host")
        self.gridLayout_17.addWidget(self.ui_interfaces_sending_kiss_lbl_host, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.ui_interfaces_sending_kiss_grp)
        self.gridLayout_2.addWidget(self.ui_interfaces_devices_grp, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.ui_interfaces_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.ui_interfaces_auth_key = QtWidgets.QLineEdit(self.groupBox)
        self.ui_interfaces_auth_key.setEnabled(False)
        self.ui_interfaces_auth_key.setObjectName("ui_interfaces_auth_key")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ui_interfaces_auth_key)
        self.ui_interfaces_auth_salt = QtWidgets.QLineEdit(self.groupBox)
        self.ui_interfaces_auth_salt.setObjectName("ui_interfaces_auth_salt")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ui_interfaces_auth_salt)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ui_interfaces_auth_btn_load = QtWidgets.QPushButton(self.groupBox)
        self.ui_interfaces_auth_btn_load.setToolTipDuration(-1)
        icon = QtGui.QIcon.fromTheme("view-refresh")
        self.ui_interfaces_auth_btn_load.setIcon(icon)
        self.ui_interfaces_auth_btn_load.setObjectName("ui_interfaces_auth_btn_load")
        self.horizontalLayout_3.addWidget(self.ui_interfaces_auth_btn_load)
        self.ui_interfaces_auth_btn_save = QtWidgets.QPushButton(self.groupBox)
        self.ui_interfaces_auth_btn_save.setToolTipDuration(-1)
        icon = QtGui.QIcon.fromTheme("document-save")
        self.ui_interfaces_auth_btn_save.setIcon(icon)
        self.ui_interfaces_auth_btn_save.setObjectName("ui_interfaces_auth_btn_save")
        self.horizontalLayout_3.addWidget(self.ui_interfaces_auth_btn_save)
        self.formLayout_3.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.formLayout_3)
        self.listView_2 = QtWidgets.QListView(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView_2.sizePolicy().hasHeightForWidth())
        self.listView_2.setSizePolicy(sizePolicy)
        self.listView_2.setObjectName("listView_2")
        self.verticalLayout.addWidget(self.listView_2)
        self.gridLayout_2.addWidget(self.groupBox, 0, 1, 1, 1)
        icon = QtGui.QIcon.fromTheme("network-wireless")
        self.ui_tabs.addTab(self.ui_interfaces_tab, icon, "")
        self.ui_settings_tab = QtWidgets.QWidget()
        self.ui_settings_tab.setObjectName("ui_settings_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.ui_settings_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ui_settings_scroll = QtWidgets.QScrollArea(self.ui_settings_tab)
        self.ui_settings_scroll.setWidgetResizable(True)
        self.ui_settings_scroll.setObjectName("ui_settings_scroll")
        self.ui_settings_scroll_contents = QtWidgets.QWidget()
        self.ui_settings_scroll_contents.setGeometry(QtCore.QRect(0, 0, 1008, 600))
        self.ui_settings_scroll_contents.setObjectName("ui_settings_scroll_contents")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.ui_settings_scroll_contents)
        self.gridLayout_8.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.ui_settings_command_handling_grp = QtWidgets.QGroupBox(self.ui_settings_scroll_contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_settings_command_handling_grp.sizePolicy().hasHeightForWidth())
        self.ui_settings_command_handling_grp.setSizePolicy(sizePolicy)
        self.ui_settings_command_handling_grp.setObjectName("ui_settings_command_handling_grp")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.ui_settings_command_handling_grp)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ui_settings_auto_retry_failed_chk = QtWidgets.QCheckBox(self.ui_settings_command_handling_grp)
        self.ui_settings_auto_retry_failed_chk.setChecked(True)
        self.ui_settings_auto_retry_failed_chk.setObjectName("ui_settings_auto_retry_failed_chk")
        self.verticalLayout_4.addWidget(self.ui_settings_auto_retry_failed_chk)
        self.ui_settings_force_retries_forever_chk = QtWidgets.QCheckBox(self.ui_settings_command_handling_grp)
        self.ui_settings_force_retries_forever_chk.setObjectName("ui_settings_force_retries_forever_chk")
        self.verticalLayout_4.addWidget(self.ui_settings_force_retries_forever_chk)
        self.ui_settings_strict_parameters_chk = QtWidgets.QCheckBox(self.ui_settings_command_handling_grp)
        self.ui_settings_strict_parameters_chk.setObjectName("ui_settings_strict_parameters_chk")
        self.verticalLayout_4.addWidget(self.ui_settings_strict_parameters_chk)
        self.ui_settings_abbreviated_seq_chk = QtWidgets.QCheckBox(self.ui_settings_command_handling_grp)
        self.ui_settings_abbreviated_seq_chk.setObjectName("ui_settings_abbreviated_seq_chk")
        self.verticalLayout_4.addWidget(self.ui_settings_abbreviated_seq_chk)
        self.ui_settings_reject_invalid_crc_chk = QtWidgets.QCheckBox(self.ui_settings_command_handling_grp)
        self.ui_settings_reject_invalid_crc_chk.setObjectName("ui_settings_reject_invalid_crc_chk")
        self.verticalLayout_4.addWidget(self.ui_settings_reject_invalid_crc_chk)
        self.gridLayout_8.addWidget(self.ui_settings_command_handling_grp, 1, 2, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem11, 1, 6, 1, 1)
        self.ui_settings_global_defaults_grp = QtWidgets.QGroupBox(self.ui_settings_scroll_contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_settings_global_defaults_grp.sizePolicy().hasHeightForWidth())
        self.ui_settings_global_defaults_grp.setSizePolicy(sizePolicy)
        self.ui_settings_global_defaults_grp.setObjectName("ui_settings_global_defaults_grp")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.ui_settings_global_defaults_grp)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.ui_settings_default_radio_timeout_spin = QtWidgets.QSpinBox(self.ui_settings_global_defaults_grp)
        self.ui_settings_default_radio_timeout_spin.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.ui_settings_default_radio_timeout_spin.setMinimum(500)
        self.ui_settings_default_radio_timeout_spin.setMaximum(10000)
        self.ui_settings_default_radio_timeout_spin.setSingleStep(100)
        self.ui_settings_default_radio_timeout_spin.setProperty("value", 4000)
        self.ui_settings_default_radio_timeout_spin.setObjectName("ui_settings_default_radio_timeout_spin")
        self.gridLayout_7.addWidget(self.ui_settings_default_radio_timeout_spin, 1, 3, 1, 1)
        self.ui_settings_default_command_delay_lbl = QtWidgets.QLabel(self.ui_settings_global_defaults_grp)
        self.ui_settings_default_command_delay_lbl.setObjectName("ui_settings_default_command_delay_lbl")
        self.gridLayout_7.addWidget(self.ui_settings_default_command_delay_lbl, 3, 0, 1, 1)
        self.ui_settings_default_parser_fn_lbl = QtWidgets.QLabel(self.ui_settings_global_defaults_grp)
        self.ui_settings_default_parser_fn_lbl.setEnabled(True)
        self.ui_settings_default_parser_fn_lbl.setObjectName("ui_settings_default_parser_fn_lbl")
        self.gridLayout_7.addWidget(self.ui_settings_default_parser_fn_lbl, 7, 0, 1, 1)
        self.ui_settings_default_radio_timeout_lbl = QtWidgets.QLabel(self.ui_settings_global_defaults_grp)
        self.ui_settings_default_radio_timeout_lbl.setObjectName("ui_settings_default_radio_timeout_lbl")
        self.gridLayout_7.addWidget(self.ui_settings_default_radio_timeout_lbl, 1, 0, 1, 2)
        self.ui_settings_default_net_retries_lbl = QtWidgets.QLabel(self.ui_settings_global_defaults_grp)
        self.ui_settings_default_net_retries_lbl.setObjectName("ui_settings_default_net_retries_lbl")
        self.gridLayout_7.addWidget(self.ui_settings_default_net_retries_lbl, 6, 0, 1, 1)
        self.ui_settings_default_ftdi_timeout_lbl = QtWidgets.QLabel(self.ui_settings_global_defaults_grp)
        self.ui_settings_default_ftdi_timeout_lbl.setObjectName("ui_settings_default_ftdi_timeout_lbl")
        self.gridLayout_7.addWidget(self.ui_settings_default_ftdi_timeout_lbl, 0, 0, 1, 3)
        self.ui_settings_default_last_frame_timeout_lbl = QtWidgets.QLabel(self.ui_settings_global_defaults_grp)
        self.ui_settings_default_last_frame_timeout_lbl.setObjectName("ui_settings_default_last_frame_timeout_lbl")
        self.gridLayout_7.addWidget(self.ui_settings_default_last_frame_timeout_lbl, 2, 0, 1, 1)
        self.ui_settings_default_command_retries_lbl = QtWidgets.QLabel(self.ui_settings_global_defaults_grp)
        self.ui_settings_default_command_retries_lbl.setObjectName("ui_settings_default_command_retries_lbl")
        self.gridLayout_7.addWidget(self.ui_settings_default_command_retries_lbl, 4, 0, 1, 1)
        self.ui_settings_default_net_timeout_lbl = QtWidgets.QLabel(self.ui_settings_global_defaults_grp)
        self.ui_settings_default_net_timeout_lbl.setObjectName("ui_settings_default_net_timeout_lbl")
        self.gridLayout_7.addWidget(self.ui_settings_default_net_timeout_lbl, 5, 0, 1, 1)
        self.ui_settings_default_ftdi_timeout_spin = QtWidgets.QSpinBox(self.ui_settings_global_defaults_grp)
        self.ui_settings_default_ftdi_timeout_spin.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.ui_settings_default_ftdi_timeout_spin.setMinimum(10)
        self.ui_settings_default_ftdi_timeout_spin.setMaximum(5000)
        self.ui_settings_default_ftdi_timeout_spin.setSingleStep(5)
        self.ui_settings_default_ftdi_timeout_spin.setProperty("value", 500)
        self.ui_settings_default_ftdi_timeout_spin.setObjectName("ui_settings_default_ftdi_timeout_spin")
        self.gridLayout_7.addWidget(self.ui_settings_default_ftdi_timeout_spin, 0, 3, 1, 1)
        self.ui_settings_default_last_frame_timeout_spin = QtWidgets.QSpinBox(self.ui_settings_global_defaults_grp)
        self.ui_settings_default_last_frame_timeout_spin.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.ui_settings_default_last_frame_timeout_spin.setMaximum(3000)
        self.ui_settings_default_last_frame_timeout_spin.setSingleStep(10)
        self.ui_settings_default_last_frame_timeout_spin.setProperty("value", 200)
        self.ui_settings_default_last_frame_timeout_spin.setObjectName("ui_settings_default_last_frame_timeout_spin")
        self.gridLayout_7.addWidget(self.ui_settings_default_last_frame_timeout_spin, 2, 3, 1, 1)
        self.ui_settings_default_command_delay_spin = QtWidgets.QSpinBox(self.ui_settings_global_defaults_grp)
        self.ui_settings_default_command_delay_spin.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.ui_settings_default_command_delay_spin.setMinimum(500)
        self.ui_settings_default_command_delay_spin.setMaximum(5000)
        self.ui_settings_default_command_delay_spin.setSingleStep(50)
        self.ui_settings_default_command_delay_spin.setObjectName("ui_settings_default_command_delay_spin")
        self.gridLayout_7.addWidget(self.ui_settings_default_command_delay_spin, 3, 3, 1, 1)
        self.ui_settings_default_command_retries_spin = QtWidgets.QSpinBox(self.ui_settings_global_defaults_grp)
        self.ui_settings_default_command_retries_spin.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.ui_settings_default_command_retries_spin.setSuffix("")
        self.ui_settings_default_command_retries_spin.setMinimum(0)
        self.ui_settings_default_command_retries_spin.setMaximum(10)
        self.ui_settings_default_command_retries_spin.setProperty("value", 3)
        self.ui_settings_default_command_retries_spin.setObjectName("ui_settings_default_command_retries_spin")
        self.gridLayout_7.addWidget(self.ui_settings_default_command_retries_spin, 4, 3, 1, 1)
        self.ui_settings_default_net_timeout_spin = QtWidgets.QSpinBox(self.ui_settings_global_defaults_grp)
        self.ui_settings_default_net_timeout_spin.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.ui_settings_default_net_timeout_spin.setMinimum(20)
        self.ui_settings_default_net_timeout_spin.setMaximum(1000)
        self.ui_settings_default_net_timeout_spin.setSingleStep(10)
        self.ui_settings_default_net_timeout_spin.setObjectName("ui_settings_default_net_timeout_spin")
        self.gridLayout_7.addWidget(self.ui_settings_default_net_timeout_spin, 5, 3, 1, 1)
        self.ui_settings_default_net_retries_spin = QtWidgets.QSpinBox(self.ui_settings_global_defaults_grp)
        self.ui_settings_default_net_retries_spin.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.ui_settings_default_net_retries_spin.setMaximum(10)
        self.ui_settings_default_net_retries_spin.setProperty("value", 3)
        self.ui_settings_default_net_retries_spin.setObjectName("ui_settings_default_net_retries_spin")
        self.gridLayout_7.addWidget(self.ui_settings_default_net_retries_spin, 6, 3, 1, 1)
        self.ui_settings_default_parser_fn_combo = QtWidgets.QComboBox(self.ui_settings_global_defaults_grp)
        self.ui_settings_default_parser_fn_combo.setEnabled(True)
        self.ui_settings_default_parser_fn_combo.setObjectName("ui_settings_default_parser_fn_combo")
        self.gridLayout_7.addWidget(self.ui_settings_default_parser_fn_combo, 7, 3, 1, 1)
        self.gridLayout_8.addWidget(self.ui_settings_global_defaults_grp, 1, 0, 2, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ui_settings_buttons_layout = QtWidgets.QHBoxLayout()
        self.ui_settings_buttons_layout.setObjectName("ui_settings_buttons_layout")
        self.ui_settings_reset_btn = QtWidgets.QPushButton(self.ui_settings_scroll_contents)
        self.ui_settings_reset_btn.setObjectName("ui_settings_reset_btn")
        self.ui_settings_buttons_layout.addWidget(self.ui_settings_reset_btn, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignBottom)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ui_settings_buttons_layout.addItem(spacerItem12)
        self.ui_settings_apply_safe_btn = QtWidgets.QPushButton(self.ui_settings_scroll_contents)
        self.ui_settings_apply_safe_btn.setEnabled(True)
        self.ui_settings_apply_safe_btn.setMinimumSize(QtCore.QSize(100, 0))
        self.ui_settings_apply_safe_btn.setCheckable(False)
        self.ui_settings_apply_safe_btn.setChecked(False)
        self.ui_settings_apply_safe_btn.setObjectName("ui_settings_apply_safe_btn")
        self.ui_settings_buttons_layout.addWidget(self.ui_settings_apply_safe_btn, 0, QtCore.Qt.AlignBottom)
        self.ui_settings_apply_btn = QtWidgets.QPushButton(self.ui_settings_scroll_contents)
        self.ui_settings_apply_btn.setMinimumSize(QtCore.QSize(100, 0))
        self.ui_settings_apply_btn.setCheckable(False)
        self.ui_settings_apply_btn.setChecked(False)
        self.ui_settings_apply_btn.setObjectName("ui_settings_apply_btn")
        self.ui_settings_buttons_layout.addWidget(self.ui_settings_apply_btn, 0, QtCore.Qt.AlignBottom)
        self.ui_settings_save_btn = QtWidgets.QPushButton(self.ui_settings_scroll_contents)
        self.ui_settings_save_btn.setObjectName("ui_settings_save_btn")
        self.ui_settings_buttons_layout.addWidget(self.ui_settings_save_btn, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.gridLayout_8.addLayout(self.ui_settings_buttons_layout, 4, 0, 1, 7)
        self.ui_settings_network_grp = QtWidgets.QGroupBox(self.ui_settings_scroll_contents)
        self.ui_settings_network_grp.setObjectName("ui_settings_network_grp")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.ui_settings_network_grp)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.ui_settings_sub_port_spin = QtWidgets.QSpinBox(self.ui_settings_network_grp)
        self.ui_settings_sub_port_spin.setMinimum(1025)
        self.ui_settings_sub_port_spin.setMaximum(65535)
        self.ui_settings_sub_port_spin.setProperty("value", 13579)
        self.ui_settings_sub_port_spin.setObjectName("ui_settings_sub_port_spin")
        self.gridLayout_9.addWidget(self.ui_settings_sub_port_spin, 4, 2, 1, 1)
        self.ui_settings_sub_port_lbl = QtWidgets.QLabel(self.ui_settings_network_grp)
        self.ui_settings_sub_port_lbl.setObjectName("ui_settings_sub_port_lbl")
        self.gridLayout_9.addWidget(self.ui_settings_sub_port_lbl, 4, 1, 1, 1)
        self.ui_settings_req_port_spin = QtWidgets.QSpinBox(self.ui_settings_network_grp)
        self.ui_settings_req_port_spin.setMinimum(1025)
        self.ui_settings_req_port_spin.setMaximum(65535)
        self.ui_settings_req_port_spin.setProperty("value", 13578)
        self.ui_settings_req_port_spin.setObjectName("ui_settings_req_port_spin")
        self.gridLayout_9.addWidget(self.ui_settings_req_port_spin, 3, 2, 1, 1)
        self.ui_settings_remote_addr_lbl = QtWidgets.QLabel(self.ui_settings_network_grp)
        self.ui_settings_remote_addr_lbl.setObjectName("ui_settings_remote_addr_lbl")
        self.gridLayout_9.addWidget(self.ui_settings_remote_addr_lbl, 0, 1, 1, 1)
        self.ui_settings_req_port_lbl = QtWidgets.QLabel(self.ui_settings_network_grp)
        self.ui_settings_req_port_lbl.setObjectName("ui_settings_req_port_lbl")
        self.gridLayout_9.addWidget(self.ui_settings_req_port_lbl, 3, 1, 1, 1)
        self.ui_settings_remote_addr_edit = QtWidgets.QLineEdit(self.ui_settings_network_grp)
        self.ui_settings_remote_addr_edit.setObjectName("ui_settings_remote_addr_edit")
        self.gridLayout_9.addWidget(self.ui_settings_remote_addr_edit, 1, 1, 1, 2)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem13, 6, 1, 1, 1)
        self.ui_settings_net_log_lbl = QtWidgets.QLabel(self.ui_settings_network_grp)
        self.ui_settings_net_log_lbl.setObjectName("ui_settings_net_log_lbl")
        self.gridLayout_9.addWidget(self.ui_settings_net_log_lbl, 2, 1, 1, 1)
        self.ui_settings_net_log_spin = QtWidgets.QSpinBox(self.ui_settings_network_grp)
        self.ui_settings_net_log_spin.setMinimum(1025)
        self.ui_settings_net_log_spin.setMaximum(65535)
        self.ui_settings_net_log_spin.setProperty("value", 13577)
        self.ui_settings_net_log_spin.setObjectName("ui_settings_net_log_spin")
        self.gridLayout_9.addWidget(self.ui_settings_net_log_spin, 2, 2, 1, 1)
        self.gridLayout_8.addWidget(self.ui_settings_network_grp, 1, 3, 2, 2)
        self.ui_settings_other = QtWidgets.QGroupBox(self.ui_settings_scroll_contents)
        self.ui_settings_other.setObjectName("ui_settings_other")
        self.formLayout = QtWidgets.QFormLayout(self.ui_settings_other)
        self.formLayout.setObjectName("formLayout")
        self.ui_settings_sat_id_label = QtWidgets.QLabel(self.ui_settings_other)
        self.ui_settings_sat_id_label.setObjectName("ui_settings_sat_id_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.ui_settings_sat_id_label)
        self.ui_settings_sat_id_combo = QtWidgets.QComboBox(self.ui_settings_other)
        self.ui_settings_sat_id_combo.setEnabled(True)
        self.ui_settings_sat_id_combo.setObjectName("ui_settings_sat_id_combo")
        self.ui_settings_sat_id_combo.addItem("")
        self.ui_settings_sat_id_combo.addItem("")
        self.ui_settings_sat_id_combo.addItem("")
        self.ui_settings_sat_id_combo.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ui_settings_sat_id_combo)
        self.gridLayout_8.addWidget(self.ui_settings_other, 2, 2, 1, 1)
        self.ui_settings_scroll.setWidget(self.ui_settings_scroll_contents)
        self.verticalLayout_3.addWidget(self.ui_settings_scroll)
        icon = QtGui.QIcon.fromTheme("emblem-system")
        self.ui_tabs.addTab(self.ui_settings_tab, icon, "")
        self.horizontalLayout_10.addWidget(self.ui_tabs)
        MainWindow.setCentralWidget(self.ui_centralwidget)
        self.ui_menu_bar = QtWidgets.QMenuBar(MainWindow)
        self.ui_menu_bar.setGeometry(QtCore.QRect(0, 0, 1050, 22))
        self.ui_menu_bar.setObjectName("ui_menu_bar")
        self.ui_file_menu = QtWidgets.QMenu(self.ui_menu_bar)
        self.ui_file_menu.setTearOffEnabled(False)
        self.ui_file_menu.setObjectName("ui_file_menu")
        self.ui_view_menu = QtWidgets.QMenu(self.ui_menu_bar)
        self.ui_view_menu.setObjectName("ui_view_menu")
        MainWindow.setMenuBar(self.ui_menu_bar)
        self.ui_statusbar = QtWidgets.QStatusBar(MainWindow)
        self.ui_statusbar.setObjectName("ui_statusbar")
        MainWindow.setStatusBar(self.ui_statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.ui_action_quit = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("application-exit")
        self.ui_action_quit.setIcon(icon)
        self.ui_action_quit.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.ui_action_quit.setObjectName("ui_action_quit")
        self.ui_action_telemetry = QtWidgets.QAction(MainWindow)
        self.ui_action_telemetry.setCheckable(True)
        icon = QtGui.QIcon.fromTheme("applications-office")
        self.ui_action_telemetry.setIcon(icon)
        self.ui_action_telemetry.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.ui_action_telemetry.setObjectName("ui_action_telemetry")
        self.ui_action_clear_console = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("edit-clear")
        self.ui_action_clear_console.setIcon(icon)
        self.ui_action_clear_console.setObjectName("ui_action_clear_console")
        self.ui_action_stop_commands = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("process-stop")
        self.ui_action_stop_commands.setIcon(icon)
        self.ui_action_stop_commands.setObjectName("ui_action_stop_commands")
        self.ui_file_menu.addAction(self.ui_action_quit)
        self.ui_view_menu.addAction(self.ui_action_telemetry)
        self.ui_view_menu.addAction(self.ui_action_clear_console)
        self.ui_menu_bar.addAction(self.ui_file_menu.menuAction())
        self.ui_menu_bar.addAction(self.ui_view_menu.menuAction())
        self.toolBar.addAction(self.ui_action_clear_console)
        self.toolBar.addAction(self.ui_action_telemetry)
        self.toolBar.addAction(self.ui_action_stop_commands)

        self.retranslateUi(MainWindow)
        self.ui_tabs.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.ui_settings_scroll, self.ui_settings_auto_retry_failed_chk)
        MainWindow.setTabOrder(self.ui_settings_auto_retry_failed_chk, self.ui_settings_force_retries_forever_chk)
        MainWindow.setTabOrder(self.ui_settings_force_retries_forever_chk, self.ui_settings_strict_parameters_chk)
        MainWindow.setTabOrder(self.ui_settings_strict_parameters_chk, self.ui_settings_abbreviated_seq_chk)
        MainWindow.setTabOrder(self.ui_settings_abbreviated_seq_chk, self.ui_settings_reject_invalid_crc_chk)
        MainWindow.setTabOrder(self.ui_settings_reject_invalid_crc_chk, self.ui_settings_default_ftdi_timeout_spin)
        MainWindow.setTabOrder(self.ui_settings_default_ftdi_timeout_spin, self.ui_settings_default_radio_timeout_spin)
        MainWindow.setTabOrder(self.ui_settings_default_radio_timeout_spin, self.ui_settings_default_last_frame_timeout_spin)
        MainWindow.setTabOrder(self.ui_settings_default_last_frame_timeout_spin, self.ui_settings_default_command_delay_spin)
        MainWindow.setTabOrder(self.ui_settings_default_command_delay_spin, self.ui_settings_default_command_retries_spin)
        MainWindow.setTabOrder(self.ui_settings_default_command_retries_spin, self.ui_settings_default_net_timeout_spin)
        MainWindow.setTabOrder(self.ui_settings_default_net_timeout_spin, self.ui_settings_default_net_retries_spin)
        MainWindow.setTabOrder(self.ui_settings_default_net_retries_spin, self.ui_settings_default_parser_fn_combo)
        MainWindow.setTabOrder(self.ui_settings_default_parser_fn_combo, self.ui_commandload_available_tbl)
        MainWindow.setTabOrder(self.ui_commandload_available_tbl, self.ui_commandload_btn_unstage)
        MainWindow.setTabOrder(self.ui_commandload_btn_unstage, self.ui_commandload_btn_stage)
        MainWindow.setTabOrder(self.ui_commandload_btn_stage, self.ui_commandload_btn_up)
        MainWindow.setTabOrder(self.ui_commandload_btn_up, self.ui_commandload_btn_down)
        MainWindow.setTabOrder(self.ui_commandload_btn_down, self.ui_commandload_btn_export)
        MainWindow.setTabOrder(self.ui_commandload_btn_export, self.ui_commandload_staged_tbl)
        MainWindow.setTabOrder(self.ui_commandload_staged_tbl, self.ui_settings_reset_btn)
        MainWindow.setTabOrder(self.ui_settings_reset_btn, self.ui_settings_apply_btn)
        MainWindow.setTabOrder(self.ui_settings_apply_btn, self.ui_settings_save_btn)
        MainWindow.setTabOrder(self.ui_settings_save_btn, self.ui_settings_remote_addr_edit)
        MainWindow.setTabOrder(self.ui_settings_remote_addr_edit, self.ui_settings_req_port_spin)
        MainWindow.setTabOrder(self.ui_settings_req_port_spin, self.ui_settings_sub_port_spin)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ELFIN Commander"))
        self.ui_tabs.setTabText(self.ui_tabs.indexOf(self.ui_console_tab), _translate("MainWindow", "Console"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Command Dispatcher"))
        self.ui_dispatch_btn_dispatch_clear_local.setText(_translate("MainWindow", " Clear"))
        self.ui_dispatch_btn_dispatch_clear_queue.setText(_translate("MainWindow", " Cancel"))
        self.ui_dispatch_label_dispatch_stats.setText(_translate("MainWindow", "Statistics Go Here"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Load Files"))
        self.ui_dispatchers_btn_load.setText(_translate("MainWindow", " Load"))
        self.ui_dispatchers_btn_upload.setText(_translate("MainWindow", " Upload"))
        self.ui_dispatchers_btn_abort.setText(_translate("MainWindow", " Abort"))
        self.ui_tabs.setTabText(self.ui_tabs.indexOf(self.ui_dispatchers_tab), _translate("MainWindow", "Commands"))
        self.ui_log_gsed_lbl.setText(_translate("MainWindow", "GSED Log"))
        self.ui_log_gsed_clear.setText(_translate("MainWindow", "Clear"))
        self.ui_tabs.setTabText(self.ui_tabs.indexOf(self.ui_log_tab), _translate("MainWindow", "Log"))
        self.ui_commandload_label_staged.setText(_translate("MainWindow", "Staged Commands"))
        self.ui_commandload_btn_up.setText(_translate("MainWindow", "Up"))
        self.ui_commandload_btn_down.setText(_translate("MainWindow", "Down"))
        self.ui_commandload_btn_export.setText(_translate("MainWindow", "Export"))
        self.ui_commandload_label_available.setText(_translate("MainWindow", "Available Commands"))
        self.ui_commandload_btn_load.setText(_translate("MainWindow", "Load"))
        self.ui_commandload_btn_delete.setText(_translate("MainWindow", "Delete"))
        self.ui_tabs.setTabText(self.ui_tabs.indexOf(self.ui_command_load_tab), _translate("MainWindow", "Command Load"))
        self.ui_interfaces_devices_grp.setTitle(_translate("MainWindow", "Devices"))
        self.ui_interfaces_devices_btn_scan.setText(_translate("MainWindow", "Scan"))
        self.ui_interfaces_devices_btn_activate.setText(_translate("MainWindow", "Activate/Deactivate"))
        self.ui_interfaces_devices_btn_connect_send.setText(_translate("MainWindow", "Connect/Disconnect Send"))
        self.ui_interfaces_devices_btn_connect_recv.setText(_translate("MainWindow", "Connect/Disconnect Recv"))
        self.ui_interfaces_sending_kiss_grp.setTitle(_translate("MainWindow", "Add Kiss Port Connection"))
        self.ui_interfaces_sending_kiss_edit_port.setText(_translate("MainWindow", "8100"))
        self.ui_interfaces_sending_kiss_btn_add.setText(_translate("MainWindow", "Add"))
        self.ui_interfaces_sending_kiss_lbl_port.setText(_translate("MainWindow", "Port Number"))
        self.ui_interfaces_sending_kiss_edit_host.setText(_translate("MainWindow", "localhost"))
        self.ui_interfaces_sending_kiss_lbl_host.setText(_translate("MainWindow", "Address/Hostname"))
        self.groupBox.setTitle(_translate("MainWindow", "Authentication"))
        self.label_4.setText(_translate("MainWindow", "Key"))
        self.label_5.setText(_translate("MainWindow", "Salt"))
        self.ui_interfaces_auth_btn_load.setToolTip(_translate("MainWindow", "Reset"))
        self.ui_interfaces_auth_btn_load.setText(_translate("MainWindow", " Refresh"))
        self.ui_interfaces_auth_btn_save.setToolTip(_translate("MainWindow", "Save"))
        self.ui_interfaces_auth_btn_save.setText(_translate("MainWindow", " Save"))
        self.ui_tabs.setTabText(self.ui_tabs.indexOf(self.ui_interfaces_tab), _translate("MainWindow", "Interface"))
        self.ui_settings_command_handling_grp.setTitle(_translate("MainWindow", "Command and Response Handling"))
        self.ui_settings_auto_retry_failed_chk.setText(_translate("MainWindow", "Auto-retry Failed Commands"))
        self.ui_settings_force_retries_forever_chk.setText(_translate("MainWindow", "Force Retries Forever"))
        self.ui_settings_strict_parameters_chk.setText(_translate("MainWindow", "Strict Parameter Checking"))
        self.ui_settings_abbreviated_seq_chk.setText(_translate("MainWindow", "Allow Abbreviated Sequences"))
        self.ui_settings_reject_invalid_crc_chk.setText(_translate("MainWindow", "Reject Invalid CRCs"))
        self.ui_settings_global_defaults_grp.setTitle(_translate("MainWindow", "Defaults"))
        self.ui_settings_default_radio_timeout_spin.setSuffix(_translate("MainWindow", " ms"))
        self.ui_settings_default_command_delay_lbl.setText(_translate("MainWindow", "Command Delay"))
        self.ui_settings_default_parser_fn_lbl.setText(_translate("MainWindow", "Parser Function"))
        self.ui_settings_default_radio_timeout_lbl.setText(_translate("MainWindow", "Radio Timeout"))
        self.ui_settings_default_net_retries_lbl.setText(_translate("MainWindow", "Network Retries"))
        self.ui_settings_default_ftdi_timeout_lbl.setText(_translate("MainWindow", "FTDI Timeout"))
        self.ui_settings_default_last_frame_timeout_lbl.setText(_translate("MainWindow", "Last Frame Timeout"))
        self.ui_settings_default_command_retries_lbl.setText(_translate("MainWindow", "Command Retries"))
        self.ui_settings_default_net_timeout_lbl.setText(_translate("MainWindow", "Network Timeout"))
        self.ui_settings_default_ftdi_timeout_spin.setSuffix(_translate("MainWindow", " ms"))
        self.ui_settings_default_last_frame_timeout_spin.setSuffix(_translate("MainWindow", " ms"))
        self.ui_settings_default_command_delay_spin.setSuffix(_translate("MainWindow", " ms"))
        self.ui_settings_default_net_timeout_spin.setSuffix(_translate("MainWindow", " ms"))
        self.ui_settings_reset_btn.setText(_translate("MainWindow", "Reset"))
        self.ui_settings_apply_safe_btn.setToolTip(_translate("MainWindow", "Apllies settings without resetting network conenctions."))
        self.ui_settings_apply_safe_btn.setText(_translate("MainWindow", "Apply (safe)"))
        self.ui_settings_apply_btn.setToolTip(_translate("MainWindow", "Note: This will reset network connection. Use apply (safe) if needed"))
        self.ui_settings_apply_btn.setText(_translate("MainWindow", "Apply"))
        self.ui_settings_save_btn.setText(_translate("MainWindow", "Save"))
        self.ui_settings_network_grp.setTitle(_translate("MainWindow", "Network"))
        self.ui_settings_sub_port_lbl.setText(_translate("MainWindow", "Publish/Subscribe Port"))
        self.ui_settings_remote_addr_lbl.setText(_translate("MainWindow", "Remote Address (GSEd)"))
        self.ui_settings_req_port_lbl.setText(_translate("MainWindow", "Request/Reply Port"))
        self.ui_settings_net_log_lbl.setText(_translate("MainWindow", "Net Logging Port"))
        self.ui_settings_other.setTitle(_translate("MainWindow", "Spacecraft"))
        self.ui_settings_sat_id_label.setText(_translate("MainWindow", "Sat ID:"))
        self.ui_settings_sat_id_combo.setItemText(0, _translate("MainWindow", "ela"))
        self.ui_settings_sat_id_combo.setItemText(1, _translate("MainWindow", "elb"))
        self.ui_settings_sat_id_combo.setItemText(2, _translate("MainWindow", "gef"))
        self.ui_settings_sat_id_combo.setItemText(3, _translate("MainWindow", "ge3"))
        self.ui_tabs.setTabText(self.ui_tabs.indexOf(self.ui_settings_tab), _translate("MainWindow", "Settings"))
        self.ui_file_menu.setTitle(_translate("MainWindow", "File"))
        self.ui_view_menu.setTitle(_translate("MainWindow", "View"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.ui_action_quit.setText(_translate("MainWindow", "Quit"))
        self.ui_action_quit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.ui_action_telemetry.setText(_translate("MainWindow", "Telemetry"))
        self.ui_action_telemetry.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.ui_action_clear_console.setText(_translate("MainWindow", "Clear Console"))
        self.ui_action_stop_commands.setText(_translate("MainWindow", "Clear Command Queue"))
        self.ui_action_stop_commands.setToolTip(_translate("MainWindow", "Clear Command Queue"))

