# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/ui/TelemetryWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TelemetryWindow(object):
    def setupUi(self, TelemetryWindow):
        TelemetryWindow.setObjectName("TelemetryWindow")
        TelemetryWindow.resize(787, 688)
        self.ui_centralwidget = QtWidgets.QWidget(TelemetryWindow)
        self.ui_centralwidget.setObjectName("ui_centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.ui_centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ui_board_tabs = QtWidgets.QTabWidget(self.ui_centralwidget)
        self.ui_board_tabs.setMovable(True)
        self.ui_board_tabs.setObjectName("ui_board_tabs")
        self.ui_overview_tab = QtWidgets.QWidget()
        self.ui_overview_tab.setObjectName("ui_overview_tab")
        self.ui_board_tabs.addTab(self.ui_overview_tab, "")
        self.ui_tests_tab = QtWidgets.QWidget()
        self.ui_tests_tab.setObjectName("ui_tests_tab")
        self.ui_board_tabs.addTab(self.ui_tests_tab, "")
        self.ui_board_fc_tab = QtWidgets.QWidget()
        self.ui_board_fc_tab.setAutoFillBackground(False)
        self.ui_board_fc_tab.setObjectName("ui_board_fc_tab")
        self.fc_memory_map = QtWidgets.QTableWidget(self.ui_board_fc_tab)
        self.fc_memory_map.setGeometry(QtCore.QRect(0, 10, 751, 511))
        self.fc_memory_map.setObjectName("fc_memory_map")
        self.fc_memory_map.setColumnCount(2)
        self.fc_memory_map.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.fc_memory_map.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fc_memory_map.setHorizontalHeaderItem(1, item)
        self.fc_memory_map.horizontalHeader().setDefaultSectionSize(175)
        self.fc_memory_map.horizontalHeader().setStretchLastSection(True)
        self.ui_board_tabs.addTab(self.ui_board_fc_tab, "")
        self.ui_board_pwr_tab = QtWidgets.QWidget()
        self.ui_board_pwr_tab.setObjectName("ui_board_pwr_tab")
        self.ui_board_tabs.addTab(self.ui_board_pwr_tab, "")
        self.ui_board_acb_tab = QtWidgets.QWidget()
        self.ui_board_acb_tab.setObjectName("ui_board_acb_tab")
        self.ui_board_tabs.addTab(self.ui_board_acb_tab, "")
        self.ui_board_pc_tab = QtWidgets.QWidget()
        self.ui_board_pc_tab.setObjectName("ui_board_pc_tab")
        self.ui_board_tabs.addTab(self.ui_board_pc_tab, "")
        self.ui_board_idpu_tab = QtWidgets.QWidget()
        self.ui_board_idpu_tab.setObjectName("ui_board_idpu_tab")
        self.ui_board_tabs.addTab(self.ui_board_idpu_tab, "")
        self.ui_board_radio_tab = QtWidgets.QWidget()
        self.ui_board_radio_tab.setObjectName("ui_board_radio_tab")
        self.ui_board_tabs.addTab(self.ui_board_radio_tab, "")
        self.ui_board_wd_tab = QtWidgets.QWidget()
        self.ui_board_wd_tab.setObjectName("ui_board_wd_tab")
        self.ui_board_tabs.addTab(self.ui_board_wd_tab, "")
        self.horizontalLayout.addWidget(self.ui_board_tabs)
        TelemetryWindow.setCentralWidget(self.ui_centralwidget)
        self.ui_statusbar = QtWidgets.QStatusBar(TelemetryWindow)
        self.ui_statusbar.setObjectName("ui_statusbar")
        TelemetryWindow.setStatusBar(self.ui_statusbar)
        self.toolBar = QtWidgets.QToolBar(TelemetryWindow)
        self.toolBar.setObjectName("toolBar")
        TelemetryWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.ui_plotting_dock = QtWidgets.QDockWidget(TelemetryWindow)
        self.ui_plotting_dock.setObjectName("ui_plotting_dock")
        self.ui_plotting_dock_contents = QtWidgets.QWidget()
        self.ui_plotting_dock_contents.setObjectName("ui_plotting_dock_contents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.ui_plotting_dock_contents)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ui_plotting_dock.setWidget(self.ui_plotting_dock_contents)
        TelemetryWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.ui_plotting_dock)
        self.actionSave = QtWidgets.QAction(TelemetryWindow)
        icon = QtGui.QIcon.fromTheme("document-save")
        self.actionSave.setIcon(icon)
        self.actionSave.setObjectName("actionSave")
        self.toolBar.addAction(self.actionSave)

        self.retranslateUi(TelemetryWindow)
        self.ui_board_tabs.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(TelemetryWindow)

    def retranslateUi(self, TelemetryWindow):
        _translate = QtCore.QCoreApplication.translate
        TelemetryWindow.setWindowTitle(_translate("TelemetryWindow", "Telemetry"))
        self.ui_board_tabs.setTabText(self.ui_board_tabs.indexOf(self.ui_overview_tab), _translate("TelemetryWindow", "Overview"))
        self.ui_board_tabs.setTabText(self.ui_board_tabs.indexOf(self.ui_tests_tab), _translate("TelemetryWindow", "Tests"))
        item = self.fc_memory_map.horizontalHeaderItem(0)
        item.setText(_translate("TelemetryWindow", "Address (Hex)"))
        item = self.fc_memory_map.horizontalHeaderItem(1)
        item.setText(_translate("TelemetryWindow", "Value"))
        self.ui_board_tabs.setTabText(self.ui_board_tabs.indexOf(self.ui_board_fc_tab), _translate("TelemetryWindow", "FC"))
        self.ui_board_tabs.setTabText(self.ui_board_tabs.indexOf(self.ui_board_pwr_tab), _translate("TelemetryWindow", "PWR"))
        self.ui_board_tabs.setTabText(self.ui_board_tabs.indexOf(self.ui_board_acb_tab), _translate("TelemetryWindow", "ACB"))
        self.ui_board_tabs.setTabText(self.ui_board_tabs.indexOf(self.ui_board_pc_tab), _translate("TelemetryWindow", "PC"))
        self.ui_board_tabs.setTabText(self.ui_board_tabs.indexOf(self.ui_board_idpu_tab), _translate("TelemetryWindow", "IDPU"))
        self.ui_board_tabs.setTabText(self.ui_board_tabs.indexOf(self.ui_board_radio_tab), _translate("TelemetryWindow", "RADIO"))
        self.ui_board_tabs.setTabText(self.ui_board_tabs.indexOf(self.ui_board_wd_tab), _translate("TelemetryWindow", "WD"))
        self.toolBar.setWindowTitle(_translate("TelemetryWindow", "toolBar"))
        self.actionSave.setText(_translate("TelemetryWindow", "Save"))

